### ISSUE TITLE
StringIndexOutOfBoundsException: length=0; index=-1

### ISSUE THREAD

**Issue by GalvinChen** [xujinyang/BiuEditText#4]
增加属性:android:digits="1234567890."
代码里设置:editText.setInputType(EditorInfo.TYPE_CLASS_PHONE);
控制EditText获取到焦点直接打开的是数字面板,报错了!

Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=-1
            at java.lang.String.indexAndLength(String.java:500)
            at java.lang.String.charAt(String.java:494)
            at me.james.biuedittext.BiuEditText$1.onTextChanged(BiuEditText.java:85)
            at android.widget.TextView.sendOnTextChanged(TextView.java:7682)
            at android.widget.TextView.setText(TextView.java:4063)
            at android.widget.TextView.setText(TextView.java:3918)
            at android.widget.EditText.setText(EditText.java:85)
            at android.widget.TextView.setText(TextView.java:3893)
            at android.widget.TextView.setTransformationMethod(TextView.java:1776)
            at android.widget.TextView.applySingleLine(TextView.java:7379)
            at android.widget.TextView.setInputType(TextView.java:4264)
            at jamesxu.biuedittext.BiuFragment.onCreateView(BiuFragment.java:23)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
            at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
            at com.qihoo360.mobilesafe.loader.c.callActivityOnStart(SourceFile:150)
            at android.app.Activity.performStart(Activity.java:6006)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by xujinyang** [comment]
tks,please update to 1.3.0
