### ISSUE TITLE
setText("")

### ISSUE THREAD

**Issue by sayhellotogithub** [xujinyang/BiuEditText#8]
report :  Caused by: java.lang.NullPointerException
                                                                            at me.james.biuedittext.BiuEditText.playFlyUp(BiuEditText.java:183)
                                                                            at me.james.biuedittext.BiuEditText.playAnaimator(BiuEditText.java:128)
                                                                            at me.james.biuedittext.BiuEditText.update(BiuEditText.java:110)
                                                                            at me.james.biuedittext.BiuEditText.access$100(BiuEditText.java:26)
                                                                            at me.james.biuedittext.BiuEditText$1.onTextChanged(BiuEditText.java:87)
                                                                            at android.widget.TextView.sendOnTextChanged(TextView.java:7079)
                                                                            at android.widget.TextView.setText(TextView.java:3550)
                                                                            at android.widget.TextView.setText(TextView.java:3405)
                                                                            at android.widget.EditText.setText(EditText.java:80)
                                                                            at android.widget.TextView.setText(TextView.java:3380)

**Comment by ssthouse** [comment]
same problem, did you solved this ?

**Comment by xujinyang** [comment]
l try to setText(""),but cannot recurrent，can you copy the code ?or try update lib to 1.4.0
